version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 100
  target-branch: master
  ignore:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 100
  target-branch: master
