name: Benchmark
on:
  push:
permissions:
  contents: read

jobs:
  typescript:
    runs-on: ubuntu-20.04
    name: TypeScript
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3

      - name: Setup node
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
        with:
          node-version: 14

      - run: npm install

      - run: node ./benchmarks/typescript
        env:
          DB_URL: ${{ secrets.DB_URL }}