name: Documentation
on:
  pull_request:
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
permissions:
  contents: read

jobs:
  lint-documentation:
    runs-on: ubuntu-latest
    name: Lint Markdown files
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 16

      - run: npm install

      - name: Lint MD-Files # run markdownlint
        run: npm run lint-md

      # enable when "eslint-markdown" can be used without errors
      # - name: Lint JS-Files # run eslint to lint the code-blocks themself
      #   run: npm run lint-js

  test-documentation:
    runs-on: ubuntu-20.04
    name: Test Generating Docs
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: git fetch --depth=1 --tags # download all tags for documentation

      - name: Setup node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 16

      - run: npm install
      - run: npm run docs:clean
      - run: npm run docs:generate
