name: Tidelift Alignment
on:
  push:
    paths:
      - '.github/workflows/tidelift-alignment.yml'
      - 'package.json'

permissions:
  contents: read

jobs:
  build:
    name: Run Tidelift to ensure approved open source packages are in use
    runs-on: ubuntu-latest
    if: github.repository == 'Automattic/mongoose'
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
      - name: Alignment
        uses: tidelift/alignment-action@8d7700fe795fc01179c1f9fa05b72a089873027d # main
        env:
          TIDELIFT_API_KEY: ${{ secrets.TIDELIFT_API_KEY }}
          TIDELIFT_ORGANIZATION: ${{ secrets.TIDELIFT_ORGANIZATION }}
          TIDELIFT_PROJECT: ${{ secrets.TIDELIFT_PROJECT }}
