name: Typescript Types
on:
  pull_request:
    paths:
      - '.github/workflows/tsd.yml'
      - 'package.json'
      - 'types/**'
      - 'test/types/**'
  push:
    paths:
      - '.github/workflows/tsd.yml'
      - 'package.json'
      - 'types/**'
      - 'test/types/**'
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint TS-Files
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 18

      - run: npm install

      - name: Lint TS-Files
        run: npm run lint-ts

  test-ts-types:
    needs:
      - lint
    runs-on: ubuntu-latest
    name: Test Typescript Types
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 14

      - run: npm install

      - name: Typings
        run: npm run test-tsd
