name: Typescript Types
on:
  pull_request:
    paths:
      - 'types/**'
      - 'test/types/**'
  push:
    paths:
      - 'types/**'
      - 'test/types/**'
permissions:
  contents: read

jobs:
  test-ts-types:
    runs-on: ubuntu-latest
    name: Typescript Types
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3

      - name: Setup node
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
        with:
          node-version: 12

      - run: npm install

      - name: Typings
        run: npm run test-tsd